name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build Docker
      run: docker-compose up -d

    - name: actions-setup-mysql
      uses: shogo82148/actions-setup-mysql@v1.5.0
      with:
        mysql-version: '8.0'
    - run: mysql -hlocalhost -P3309 -ubooks -pbooks -Dbooks<./migration/sql/createTable.sql

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
